export const AUTHORIZATION_PROCESS = 'AUTHORIZATION_PROCESS';
export const AUTHORIZATION_PROCESS_SUCCESS = 'AUTHORIZATION_PROCESS_SUCCESS';
export const AUTHORIZATION_PROCESS_FAILED = 'AUTHORIZATION_PROCESS_FAILED';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED';